# Install:    conda env create -f environment.yml
# Activate:   conda activate ism
# Deactivate: conda deactivate

name: ism

channels:
  - conda-forge
  - astropy

dependencies:
  - python>=3.9
  - numpy>=1.22
  - scipy>=1.7
  - matplotlib>=3.5.3
  - astropy>=5.0
  - click
  - photutils>=1.9
  - spectral-cube>=0.6
